class Language:
    """Class representing general language."""

    def __init__(
        self,
        upload_files_title,
        upload_files_text,
        upload_files_from_pc,
        upload_files_from_pc_error,
        upload_file_from_url,
        upload_file_from_url_error,
        manage_files_title,
        no_uploaded_files_text,
        confirm_title,
        confirm_text,
        yes_button_title,
        no_button_title,
        delete_button_title,
        visualized_button_title,
        back_button_title,
        cancel_button_title,
        upload_files_button_title,
        manage_files_button_title,
        user_guide_button_title,
        previous_file_tooltip,
        player_tooltip,
        next_file_tooltip,
        picker_mode_points_tooltip,
        picker_mode_cells_tooltip,
        toggle_axes_info_tooltip,
        reset_camera_tooltip,
        change_theme_tooltip,
        file_name_select_title,
        data_array_select_title,
        representation_select_title,
        representation_select_item_points,
        representation_select_item_slice,
        representation_select_item_surface,
        representation_select_item_surface_with_edges,
        representation_select_item_wireframe,
        color_map_select_title,
        color_map_select_item_cool_to_warm,
        color_map_select_item_grayscale,
        point_info_title,
        cell_info_title,
        section_slice_title,
        slice_orientation_select_title,
        slice_position_slider_title,
        section_zoom_title,
        section_zoom_tooltip,
        section_zoom_slider_title,
        zoom_in_tooltip,
        zoom_out_tooltip,
        section_translation_title,
        section_translation_tooltip,
        section_translation_slider_title,
        translate_x_axis_plus_tooltip,
        translate_x_axis_minus_tooltip,
        translate_y_axis_plus_tooltip,
        translate_y_axis_minus_tooltip,
        translate_z_axis_plus_tooltip,
        translate_z_axis_minus_tooltip,
        section_rotation_title,
        section_rotation_tooltip,
        section_rotation_slider_title,
        rotate_x_axis_plus_tooltip,
        rotate_x_axis_minus_tooltip,
        rotate_y_axis_plus_tooltip,
        rotate_y_axis_minus_tooltip,
        rotate_z_axis_plus_tooltip,
        rotate_z_axis_minus_tooltip,
    ):
        self.__words = {
            "upload_files_title": upload_files_title,
            "upload_files_text": upload_files_text,
            "upload_files_from_pc": upload_files_from_pc,
            "upload_files_from_pc_error": upload_files_from_pc_error,
            "upload_file_from_url": upload_file_from_url,
            "upload_file_from_url_error": upload_file_from_url_error,
            "manage_files_title": manage_files_title,
            "no_uploaded_files_text": no_uploaded_files_text,
            "confirm_title": confirm_title,
            "confirm_text": confirm_text,
            "yes_button_title": yes_button_title,
            "no_button_title": no_button_title,
            "delete_button_title": delete_button_title,
            "visualized_button_title": visualized_button_title,
            "back_button_title": back_button_title,
            "cancel_button_title": cancel_button_title,
            "upload_files_button_title": upload_files_button_title,
            "manage_files_button_title": manage_files_button_title,
            "user_guide_button_title": user_guide_button_title,
            "previous_file_tooltip": previous_file_tooltip,
            "player_tooltip": player_tooltip,
            "next_file_tooltip": next_file_tooltip,
            "picker_mode_points_tooltip": picker_mode_points_tooltip,
            "picker_mode_cells_tooltip": picker_mode_cells_tooltip,
            "toggle_axes_info_tooltip": toggle_axes_info_tooltip,
            "reset_camera_tooltip": reset_camera_tooltip,
            "change_theme_tooltip": change_theme_tooltip,
            "file_name_select_title": file_name_select_title,
            "data_array_select_title": data_array_select_title,
            "representation_select_title": representation_select_title,
            "representation_select_item_points": representation_select_item_points,
            "representation_select_item_slice": representation_select_item_slice,
            "representation_select_item_surface": representation_select_item_surface,
            "representation_select_item_surface_with_edges": representation_select_item_surface_with_edges,
            "representation_select_item_wireframe": representation_select_item_wireframe,
            "color_map_select_title": color_map_select_title,
            "color_map_select_item_cool_to_warm": color_map_select_item_cool_to_warm,
            "color_map_select_item_grayscale": color_map_select_item_grayscale,
            "point_info_title": point_info_title,
            "cell_info_title": cell_info_title,
            "section_slice_title": section_slice_title,
            "slice_orientation_select_title": slice_orientation_select_title,
            "slice_position_slider_title": slice_position_slider_title,
            "section_zoom_title": section_zoom_title,
            "section_zoom_tooltip": section_zoom_tooltip,
            "section_zoom_slider_title": section_zoom_slider_title,
            "zoom_in_tooltip": zoom_in_tooltip,
            "zoom_out_tooltip": zoom_out_tooltip,
            "section_translation_title": section_translation_title,
            "section_translation_tooltip": section_translation_tooltip,
            "section_translation_slider_title": section_translation_slider_title,
            "translate_x_axis_plus_tooltip": translate_x_axis_plus_tooltip,
            "translate_x_axis_minus_tooltip": translate_x_axis_minus_tooltip,
            "translate_y_axis_plus_tooltip": translate_y_axis_plus_tooltip,
            "translate_y_axis_minus_tooltip": translate_y_axis_minus_tooltip,
            "translate_z_axis_plus_tooltip": translate_z_axis_plus_tooltip,
            "translate_z_axis_minus_tooltip": translate_z_axis_minus_tooltip,
            "section_rotation_title": section_rotation_title,
            "section_rotation_tooltip": section_rotation_tooltip,
            "section_rotation_slider_title": section_rotation_slider_title,
            "rotate_x_axis_plus_tooltip": rotate_x_axis_plus_tooltip,
            "rotate_x_axis_minus_tooltip": rotate_x_axis_minus_tooltip,
            "rotate_y_axis_plus_tooltip": rotate_y_axis_plus_tooltip,
            "rotate_y_axis_minus_tooltip": rotate_y_axis_minus_tooltip,
            "rotate_z_axis_plus_tooltip": rotate_z_axis_plus_tooltip,
            "rotate_z_axis_minus_tooltip": rotate_z_axis_minus_tooltip,
        }

    @property
    def words(self):
        return self.__words
