import mri_viewer.app.constants as const

class Language:
    def __init__(
        self,
        previous_file_tooltip,
        player_tooltip,
        next_file_tooltip,
        picker_mode_points_tooltip,
        picker_mode_cells_tooltip,
        toggle_axes_tooltip,
        reset_camera_tooltip,
        change_theme_tooltip,
        upload_files_title,
        file_name_select_title,
        data_array_select_title,
        representation_select_title,
        representation_select_item_points,
        representation_select_item_slice,
        representation_select_item_surface,
        representation_select_item_surface_with_edges,
        representation_select_item_wireframe,
        point_information_title,
        cell_information_title,
        x_axis_title,
        y_axis_title,
        z_axis_title,
        section_slice_title,
        slice_orientation_select_title,
        slice_position_slider_title,
        section_zoom_title,
        section_zoom_tooltip,
        zoom_in_tooltip,
        zoom_out_tooltip,
        zoom_factor_slider_title,
        section_translation_title,
        section_translation_tooltip,
        translate_x_axis_plus_tooltip,
        translate_x_axis_minus_tooltip,
        translate_y_axis_plus_tooltip,
        translate_y_axis_minus_tooltip,
        translate_z_axis_plus_tooltip,
        translate_z_axis_minus_tooltip,
        translation_factor_slider_title,
        section_rotation_title,
        section_rotation_tooltip,
        rotate_x_axis_plus_tooltip,
        rotate_x_axis_minus_tooltip,
        rotate_y_axis_plus_tooltip,
        rotate_y_axis_minus_tooltip,
        rotate_z_axis_plus_tooltip,
        rotate_z_axis_minus_tooltip,
        rotation_factor_slider_title,
    ):
        self._words = {
            "previous_file_tooltip": previous_file_tooltip,
            "player_tooltip": player_tooltip,
            "next_file_tooltip": next_file_tooltip,
            "picker_mode_points_tooltip": picker_mode_points_tooltip,
            "picker_mode_cells_tooltip": picker_mode_cells_tooltip,
            "toggle_axes_tooltip": toggle_axes_tooltip,
            "reset_camera_tooltip": reset_camera_tooltip,
            "change_theme_tooltip": change_theme_tooltip,
            "upload_files_title": upload_files_title,
            "file_name_select_title": file_name_select_title,
            "data_array_select_title": data_array_select_title,
            "representation_select_title": representation_select_title,
            "current_representation_items": [
                {
                    "title": representation_select_item_points,
                    "value": const.Representation.Points,
                },
                {
                    "title": representation_select_item_slice,
                    "value": const.Representation.Slice,
                },
                {
                    "title": representation_select_item_surface,
                    "value": const.Representation.Surface,
                },
                {
                    "title": representation_select_item_surface_with_edges,
                    "value": const.Representation.SurfaceWithEdges,
                },
                {
                    "title": representation_select_item_wireframe,
                    "value": const.Representation.Wireframe,
                },
            ],
            "point_information_title": point_information_title,
            "cell_information_title": cell_information_title,
            "x_axis_title": x_axis_title,
            "y_axis_title": y_axis_title,
            "z_axis_title": z_axis_title,
            "section_slice_title": section_slice_title,
            "slice_orientation_select_title": slice_orientation_select_title,
            "slice_position_slider_title": slice_position_slider_title,
            "section_zoom_title": section_zoom_title,
            "section_zoom_tooltip": section_zoom_tooltip,
            "zoom_in_tooltip": zoom_in_tooltip,
            "zoom_out_tooltip": zoom_out_tooltip,
            "zoom_factor_slider_title": zoom_factor_slider_title,
            "section_translation_title": section_translation_title,
            "section_translation_tooltip": section_translation_tooltip,
            "translate_x_axis_plus_tooltip": translate_x_axis_plus_tooltip,
            "translate_x_axis_minus_tooltip": translate_x_axis_minus_tooltip,
            "translate_y_axis_plus_tooltip": translate_y_axis_plus_tooltip,
            "translate_y_axis_minus_tooltip": translate_y_axis_minus_tooltip,
            "translate_z_axis_plus_tooltip": translate_z_axis_plus_tooltip,
            "translate_z_axis_minus_tooltip": translate_z_axis_minus_tooltip,
            "translation_factor_slider_title": translation_factor_slider_title,
            "section_rotation_title": section_rotation_title,
            "section_rotation_tooltip": section_rotation_tooltip,
            "rotate_x_axis_plus_tooltip": rotate_x_axis_plus_tooltip,
            "rotate_x_axis_minus_tooltip": rotate_x_axis_minus_tooltip,
            "rotate_y_axis_plus_tooltip": rotate_y_axis_plus_tooltip,
            "rotate_y_axis_minus_tooltip": rotate_y_axis_minus_tooltip,
            "rotate_z_axis_plus_tooltip": rotate_z_axis_plus_tooltip,
            "rotate_z_axis_minus_tooltip": rotate_z_axis_minus_tooltip,
            "rotation_factor_slider_title": rotation_factor_slider_title,
        }

    @property
    def words(self):
        return self._words
